### ISSUE TITLE
ROM Test

### ISSUE THREAD

**Issue by rittwage-zz** [stid/kick-c64-dead-test#1]
Not a bug or an issue, but it would be nice if you could add the little BASIC/KERNAL/CHAR rom test from the diag cart.  

Here it is:
                              ;KERNAL/BASIC/CHARAC ROM test
I890E  LDX #$09
I8910  LDA F993C,X            ;"KERNAL ROM"
       STA F0568,X
       DEX
       BPL I8910
       LDX #$08
I891B  LDA F9933,X            ;"BASIC"
       STA F0590,X
       DEX
       BPL I891B
       LDX #$09
I8926  LDA F9946,X            ;"CHARAC"
       STA F05B8,X
       DEX
       BPL I8926

                              ;KERNAL ROM TEST       
       LDA #$37
       STA A01
       LDA #>$E000
       STA AF9
       LDA #$20               ;$2000 of mem to test
       STA A0F
       LDA #$00
       STA AF8
       TAY
       CLC
I8941  ADC (PF8),Y
       INY
       BNE I8941
       INC AF9
       DEC A0F
       BNE I8941
       ADC #$00
       PHA
       LDA AFF80              ;Kernal Version Number
       CMP #$AA
       BEQ I896A
       CMP #$00
       BEQ I8962
       PLA
       CMP #$E0
       BEQ I8972              ;"OK"
       JMP I8983              ;"BAD"
I8962  PLA
       CMP #$E1
       BEQ I8972              ;"OK"
       JMP I8983              ;"BAD"
I896A  PLA
       CMP #$E1
       BEQ I8972              ;"OK"
       JMP I8983              ;"BAD"

I8972  LDA #$37               ;"Kernal ROM OK"
       STA A01
       LDA #$0F               ;"O"
       STA A0575
       LDA #$0B               ;"K"
       STA A0576
       JMP I89A1
       
I8983  LDA #$37               ;"Kernal ROM BAD"
       STA A01
       LDA #$02               ;"B"
       STA A0575
       LDA #$01               ;"A"
       STA A0576
       LDA #$04               ;"D"
       STA A0577
       LDA #$02
       STA AD975
       STA AD976
       STA AD977
       
                              ;BASIC ROM TEST
I89A1  LDA #$37
       STA A01
       LDA #>$A000
       STA AF9
       LDA #$20               ;$2000 of mem to test
       STA A0F
       LDA #$00
       STA AF8
       TAY
       CLC
I89B3  ADC (PF8),Y
       INY
       BNE I89B3
       INC AF9
       DEC A0F
       BNE I89B3
       ADC #$00
       CMP #$A1
       BNE I89D5
       LDA #$37
       STA A01
       LDA #$0F               ;"O"
       STA A059D
       LDA #$0B               ;"K"
       STA A059E
       JMP I89F3

I89D5  LDA #$37               ;BASIC ROM "BAD"
       STA A01
       LDA #$02               ;"B"
       STA A059D
       LDA #$01               ;"A"
       STA A059E
       LDA #$04               ;"D"
       STA A059F
       LDA #$02
       STA AD99D
       STA AD99E
       STA AD99F
       
                              ;CHARACTER ROM TEST
I89F3  LDA #$33
       STA A01
       LDA #>$D000
       STA AF9
       LDA #$10               ;$1000 of mem
       STA A0F
       LDA #$00
       STA AF8
       TAY
       CLC
I8A05  ADC (PF8),Y
       INY
       BNE I8A05
       INC AF9
       DEC A0F
       BNE I8A05
       ADC #$00
       CMP #$F7
       BNE I8A25
       LDA #$37
       STA A01
       LDA #$0F               ;"O"
       STA A05C5
       LDA #$0B               ;"K"
       STA A05C6
       RTS

I8A25  LDA #$37               ;CHAR ROM "BAD"
       STA A01
       LDA #$02               ;"B"
       STA A05C5
       LDA #$01               ;"A"
       STA A05C6
       LDA #$04               ;"D"
       STA A05C7
       LDA #$02
       STA AD9C5
       STA AD9C6
       STA AD9C7
       RTS

**Comment by rittwage-zz** [comment]
It occured to me this may not be possible. Since the dead test runs in "ultimax" mode, you may be locked down without access to the ROMs for testing at all.

**Comment by stid** [comment]
O you are right @rittwage - that'a why Harness test is the one doing it - they are running in standard gaming - $8000.
